### ISSUE TITLE
Unlimited score bug

### ISSUE THREAD

**Issue by PokeyOne** [DVLP/LinkOfDeath#1]
At around a score of 1500 it get to a point where you just circle your mouse around the screen a bunch and the ball goes off the screen. Never to be found again...

**Comment by DVLP** [comment]
When difficulty gets to negative values then calculations are becoming ridiculous so the link travels into outer space. The formula needs to be updated or "level up" be added after beating the difficulty countdown.

**Comment by AngryLifeender** [comment]
For me it just travels to a random corner of the screen.

**Comment by thattomperson** [comment]
I have same problem as Angry

**Comment by thattomperson** [comment]
I'll see if i can submit a pr when I get home from work

**Comment by Titanic4** [comment]
I've made a pull request, which fixes the issue and the score count has added "Score:" to indicate where the score is located.
