### ISSUE TITLE
Unsupported/Incorrect ("Correct") browser notification

### ISSUE THREAD

**Issue by adavis444** [DVLP/LinkOfDeath#12]
The link of death is only truly playable with the Chrome, Chromium, and Opera browsers. Using Firefox, Safari, IE, or Edge, visitors to linkofdeath.com may fail to see the point.

Perhaps the browser could be detected, and if that browser happens to be one of the unsupported browsers, a pop-up recommends something like "This browser is not supported. For the full experience please use Google Chrome, Opera, or Chromium." with a clickable button "I understand" or "Play anyway".

**Comment by DVLP** [comment]
As more people started to play the game it's a good idea to support other browsers. Now there's a game-over screen which explains the motivation behind this project.
