### ISSUE TITLE
No movement until mouse is moved

### ISSUE THREAD

**Issue by brettwhiteman** [DVLP/LinkOfDeath#7]
If you refresh the page and don't move your mouse at all the feared LOD never chases you

**Comment by DVLP** [comment]
Mouse has to send at least one event to reveal it's cordinates. Adding a start screen with "click to start" can be a good workaround for this problem.

**Comment by DVLP** [comment]
Now the game just won't start adding score until the mouse has been moved. Also after 1000ms of mouse inactivity the score will stop being counted.
