### ISSUE TITLE
Possible to cheat by moving the mouse out of the page

### ISSUE THREAD

**Issue by quat1024** [DVLP/LinkOfDeath#9]
If you move your mouse outside of the window, the link will stay wherever your mouse was last (black ball), so your "real" mouse won't hover over the link and trigger the crash... Of course you can't make the link run off the page and chase down your dirty cheater mouse, as much fun as _that_ would be.

But I suppose you could pause the game and invalidate the score if the mouse leaves the page.

**Comment by DVLP** [comment]
Fixed. No more score counting when mouse is inactive on a page after 1000ms timeout.
